// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ArchiveDistance struct {
	Distance int64    `json:"distance"`
	Archive  *Archive `json:"archive"`
}

type License struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	GroupID   *int64  `json:"group_id"`
	GroupName *string `json:"group_name"`
}

type UploadedArchive struct {
	Extracted bool     `json:"extracted"`
	Archive   *Archive `json:"archive"`
}
