package editDistance

var OPERATION_INSERT_COST int = 20
var OPERATION_DELETE_COST int = 2
var OPERATION_SUBSTITUTE_COST int = 30
var OPERATION_SUBSTITUTE_CASE_COST int = 2
var OPERATION_TRANSPOSE_COST int = 10
var DISTANCE_MAX int = 75
var DISTANCE_MAX_NIL int = -1
